/**
 * DO NOT MODIFY THIS FILE.
 * 
 * This file is autogenerated during the build process.
 * Any manual changes will be overwritten in the next build.
 * Please make changes in the source files and rebuild as necessary.
 */

import { rest, getFetcher } from "../core/request";
import config from '../core/config';

// Types
{{#with endpoint_types}}
    {{{ generateImport endpoints '../types/splitwise' }}}
{{/with}}
import type { AuthClient } from "../types/auth"
import type { RestOptions } from "../types/request";
import type { OperationQueryParams, OperationRequestBodyContent } from "../types/utils"

export class Client {
    #auth: AuthClient;
    #defaultRequestOptions: RestOptions

    constructor(auth: AuthClient) {
        this.#auth = auth
        this.#defaultRequestOptions = {
            auth: this.#auth,
            fetcher: getFetcher(),
            endpoint: '',
            method: 'GET',
            baseUrl: config.api_url,
        }
    }

    {{#each properties}}
        {{> propertyTemplate propertyName=this.propertyName description=this.description functions=this.functions}}
    {{/each}}
}