/**
 * DO NOT MODIFY THIS FILE.
 * 
 * This file is autogenerated during the build process (by openapi-typescript).
 * Any manual changes will be overwritten in the next build.
 * Please make changes in the source files and rebuild as necessary.
 */

{{{ openApiTypeString }}}

{{#each operations}}
    export type {{ this }} = operations['{{ this }}']
{{/each}}
